### ISSUE TITLE
Include all files in jar creation

### ISSUE THREAD

**Issue by bduff9** [hounshell/gulp-javac#5]
I have my gulp script working to compile my java files to class files and then package them up into a jar.  However, this jar is much smaller than one created correctly with Eclipse.  When I compare the contents of the two, I see that there are many non-class files (i.e. xml, json, properties, etc.) being left out of the jar creation.

I see for the unjar command there is the include all files option, however there doesn't seem to be anything similar for the jar command.  I was also going to try and break this into two separate tasks (one for class file creation and then one for jar creation) however the normal way I would do that with promises doesn't seem to work here.

How would I go about this, where I need to first compile my java files and then include them and every other file in my src folder in the resulting jar?  Thanks in advance!

**Comment by hounshell** [comment]
The jar component is a pretty thin wrapper around the actual jar command line tool.  I mean, all of them are, but the jar one is thinner.  So any files that get piped to it should end up in the jar.  There's a recipe in the README for repackaging jars that should work pretty well, but here it is in a different layout:

```js
const merge = require('merge-stream');

const libraries = './lib/**/*.jar';

var classes = gulp.src('./src/**/*.java').pipe(javac.javac().addLibraries(libraries));
var library_classes = gulp.src(libraries).pipe(javac.unjar());
var other_files = gulp.src('./assets/**/*');

merge(class, library_classes, other_files).pipe(jar('example.jar'));
```

I just noticed a typo in the README, so I'll fix that when I get a chance.  The idea is to use [merge-stream](https://www.npmjs.com/package/merge-stream) to generate a single stream that includes everything you want in the jar.  

The jar pipe expects each file's [base](https://github.com/gulpjs/vinyl#filebase) and [relative](https://github.com/gulpjs/vinyl#filerelative) paths to be set. If you use gulp.src() like above they should be set, but may not be exactly what you expect.  You may have to twiddle [gulp.src() options](https://github.com/gulpjs/gulp/blob/master/docs/API.md#optionsbase).  Also, [debug-stream](https://www.npmjs.com/package/debug-stream) is a good resource for debugging what's going on in your file streams.

Now, if those files are being generated by Eclipse, then that's a little beyond the scope here.  My original reason for building this was to actually [build Android apks](https://www.npmjs.com/package/gulp-android), and I isolated the Java work because I felt like it was useful in a broader scope.

**Comment by bduff9** [comment]
Yes that makes sense.  I saw the example of using merge-stream but for some reason wasn't sure that would work for me.  Regardless, your code above pointed me in the right direction so it seems like this is now working for me.  Thank you very much!
